"""Compute claim statistics for a review and emit STATS.md.

    python3 src/claim_stats.py reviews/foo
    # writes reviews/foo/phase3/outputs/STATS.md and prints a one-line summary

Reads:
- reviews/<slug>/phase1/outputs/CLAIMS.md
- reviews/<slug>/phase2/outputs/VERIFICATION.md  (optional)
- reviews/<slug>/phase2/outputs/graph.v2.json    (optional, for group-level rows)

Writes:
- reviews/<slug>/phase3/outputs/STATS.md

The numbers are mechanical — no LLM. STATS.md is data; REPORT.md is prose
written by the report_writer agent that consumes STATS.md.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from highlight_paper import parse_claims_md, parse_verification_md  # noqa: E402

# Closed lists from the conventions, used to keep table row order stable.
CLAIM_TYPES = (
    "result", "method", "prior_work", "background_fact",
    "assumption", "interpretation", "definition", "UNCLASSIFIED",
)
VERDICTS = ("PASS", "FAIL", "INCONCLUSIVE", "NOT_CHECKED")
CONFIDENCES = ("high", "medium", "low")


def md_table(rows: list[list[str]], header: list[str]) -> str:
    widths = [max(len(str(r[i])) for r in [header, *rows]) for i in range(len(header))]
    sep = "|" + "|".join("-" * (w + 2) for w in widths) + "|"
    def fmt(cells):
        return "| " + " | ".join(str(c).ljust(w) for c, w in zip(cells, widths)) + " |"
    return "\n".join([fmt(header), sep, *(fmt(r) for r in rows)])


def stats(claims: dict, verdicts: dict, graph: dict | None) -> dict:
    n = len(claims)

    # By type.
    type_counts = Counter(c.get("type") or "UNCLASSIFIED" for c in claims.values())

    # Confidence (extraction) — note CLAIMS.md may not parse confidence into a
    # column; if missing, treat as unknown.
    confidence_counts = Counter(c.get("confidence", "") or "(unknown)" for c in claims.values())

    # Hedged.
    hedged_counts = Counter(
        "hedged" if str(c.get("hedged", "")).lower() == "true" else "not hedged"
        for c in claims.values()
    )

    # Verdict (per claim, mapping NOT_CHECKED for unverified).
    per_claim_verdict: dict[str, str] = {}
    for cid in claims:
        v = verdicts.get(cid)
        per_claim_verdict[cid] = v["verdict"] if v else "NOT_CHECKED"
    verdict_counts = Counter(per_claim_verdict.values())

    # Type × verdict.
    type_verdict: dict[tuple[str, str], int] = Counter()
    for cid, claim in claims.items():
        t = claim.get("type") or "UNCLASSIFIED"
        type_verdict[(t, per_claim_verdict[cid])] += 1

    # Methods used (verifier-side).
    method_counts = Counter(
        v["method"] for v in verdicts.values() if v.get("method")
    )

    # INCONCLUSIVE reasons.
    reason_counts = Counter(
        v["reason"] for v in verdicts.values()
        if v.get("verdict") == "INCONCLUSIVE" and v.get("reason")
    )

    # Coverage.
    attempted = sum(1 for v in verdicts.values() if v["verdict"] in ("PASS", "FAIL", "INCONCLUSIVE"))
    passed = verdict_counts.get("PASS", 0)
    failed = verdict_counts.get("FAIL", 0)
    inconclusive = verdict_counts.get("INCONCLUSIVE", 0)
    not_checked = verdict_counts.get("NOT_CHECKED", 0)

    # Per group (if graph available).
    groups_summary = []
    if graph:
        group_by_id = {g["id"]: g for g in graph.get("groups", [])}
        members: dict[str, list[str]] = {gid: [] for gid in group_by_id}
        for c in graph.get("claims", []):
            if c.get("parent") in members:
                members[c["parent"]].append(c["id"])
        for gid, g in group_by_id.items():
            child_ids = members.get(gid, [])
            child_verdicts = Counter(per_claim_verdict.get(cid, "NOT_CHECKED") for cid in child_ids)
            groups_summary.append({
                "id": gid,
                "title": g.get("title", gid),
                "claim_count": len(child_ids),
                "verdict": g.get("verdict", "NOT_CHECKED"),
                "breakdown": dict(child_verdicts),
            })

    return {
        "n_claims": n,
        "n_groups": len(graph.get("groups", [])) if graph else None,
        "type_counts": type_counts,
        "confidence_counts": confidence_counts,
        "hedged_counts": hedged_counts,
        "verdict_counts": verdict_counts,
        "type_verdict": type_verdict,
        "method_counts": method_counts,
        "reason_counts": reason_counts,
        "attempted": attempted,
        "passed": passed,
        "failed": failed,
        "inconclusive": inconclusive,
        "not_checked": not_checked,
        "groups_summary": groups_summary,
    }


def render_stats_md(slug: str, s: dict) -> str:
    n = s["n_claims"]
    out: list[str] = [
        f"# Claim statistics — {slug}",
        "",
        "Generated by `src/claim_stats.py`. Numbers are mechanical from",
        "`CLAIMS.md`, `VERIFICATION.md`, and (if present) `graph.v2.json`.",
        "",
        "## Totals",
        "",
        f"- **{n}** claims extracted",
    ]
    if s["n_groups"] is not None:
        out.append(f"- **{s['n_groups']}** groups in the graph")
    out.append("")

    # By type.
    out += [
        "## By type",
        "",
        md_table(
            [[t, str(s["type_counts"].get(t, 0))]
             for t in CLAIM_TYPES if s["type_counts"].get(t, 0)],
            ["type", "count"],
        ),
        "",
    ]

    # Extraction confidence.
    out += [
        "## By extraction confidence",
        "",
        md_table(
            [[c, str(s["confidence_counts"].get(c, 0))]
             for c in (*CONFIDENCES, "(unknown)")
             if s["confidence_counts"].get(c, 0)],
            ["confidence", "count"],
        ),
        "",
    ]

    # Hedged.
    out += [
        "## Hedging",
        "",
        f"- {s['hedged_counts'].get('hedged', 0)} hedged",
        f"- {s['hedged_counts'].get('not hedged', 0)} not hedged",
        "",
    ]

    # Verdict.
    out += [
        "## By verdict",
        "",
        md_table(
            [[v, str(s["verdict_counts"].get(v, 0))] for v in VERDICTS],
            ["verdict", "count"],
        ),
        "",
    ]

    # Type × verdict.
    types_present = [t for t in CLAIM_TYPES if s["type_counts"].get(t, 0)]
    if types_present:
        rows = []
        for t in types_present:
            rows.append([
                t,
                *(str(s["type_verdict"].get((t, v), 0)) for v in VERDICTS),
            ])
        out += [
            "## Type × verdict",
            "",
            md_table(rows, ["type", *VERDICTS]),
            "",
        ]

    # Coverage.
    pct = lambda num, denom: f"{(100 * num / denom):.1f}%" if denom else "—"
    out += [
        "## Coverage",
        "",
        f"- {s['attempted']} / {n} claims ({pct(s['attempted'], n)}) had a verification attempt",
    ]
    if s["attempted"]:
        out += [
            f"- {s['passed']} / {s['attempted']} ({pct(s['passed'], s['attempted'])}) of attempts passed",
            f"- {s['failed']} / {s['attempted']} ({pct(s['failed'], s['attempted'])}) failed",
            f"- {s['inconclusive']} / {s['attempted']} ({pct(s['inconclusive'], s['attempted'])}) inconclusive",
        ]
    out.append("")

    # Methods used.
    if s["method_counts"]:
        out += [
            "## Verification methods used",
            "",
            md_table(
                [[m, str(c)] for m, c in s["method_counts"].most_common()],
                ["method", "count"],
            ),
            "",
        ]

    # INCONCLUSIVE reasons.
    if s["reason_counts"]:
        out += [
            "## INCONCLUSIVE reasons",
            "",
            md_table(
                [[r, str(c)] for r, c in s["reason_counts"].most_common()],
                ["reason", "count"],
            ),
            "",
        ]

    # Per group.
    if s["groups_summary"]:
        rows = []
        for g in s["groups_summary"]:
            bd = g["breakdown"]
            bd_str = ", ".join(f"{k} {v}" for k, v in bd.items()) or "—"
            rows.append([
                g["id"],
                g["title"],
                str(g["claim_count"]),
                g["verdict"],
                bd_str,
            ])
        out += [
            "## Per group",
            "",
            md_table(rows, ["id", "title", "claims", "group_verdict", "breakdown"]),
            "",
        ]

    return "\n".join(out)


def one_line_summary(slug: str, s: dict) -> str:
    return (
        f"{slug}: {s['n_claims']} claims · "
        f"PASS={s['passed']} FAIL={s['failed']} "
        f"INCONCLUSIVE={s['inconclusive']} NOT_CHECKED={s['not_checked']}"
    )


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("review_dir", type=Path, help="path to reviews/<slug>/")
    p.add_argument("--out", type=Path, help="override STATS.md path")
    p.add_argument("--print", action="store_true",
                   help="also print STATS.md content to stdout")
    args = p.parse_args()

    review = args.review_dir
    if not review.is_dir():
        print(f"error: {review} is not a directory", file=sys.stderr)
        return 2

    claims_md = review / "phase1" / "outputs" / "CLAIMS.md"
    verification_md = review / "phase2" / "outputs" / "VERIFICATION.md"
    graph_v2_json = review / "phase2" / "outputs" / "graph.v2.json"
    out_path = args.out or (review / "phase3" / "outputs" / "STATS.md")

    if not claims_md.exists():
        print(f"error: CLAIMS.md not found at {claims_md}", file=sys.stderr)
        return 2

    claims = parse_claims_md(claims_md)
    verdicts = parse_verification_md(verification_md)
    graph = json.loads(graph_v2_json.read_text()) if graph_v2_json.exists() else None

    s = stats(claims, verdicts, graph)
    md = render_stats_md(review.name, s)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md + "\n")
    print(f"wrote {out_path}")
    print(f"  {one_line_summary(review.name, s)}")
    if args.print:
        print()
        print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
